#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend bela-frontend
    bind *:80
    mode http
    default_backend bela-backend
    timeout client 30s

backend bela-backend
    mode http
    balance roundrobin
    server backend1 98.80.11.37:80 check
    server backend2 52.91.49.196:80 check
    timeout connect 30s
    timeout server 30s
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# restart haproxy
sudo service haproxy restart
