#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend bela-frontend
        bind *:80
        mode http
        default_backend bela-backend
backend bela-backend
        balance roundrobin
        server backend1 98.80.11.37 check
        server backend2 52.91.49.196 check
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy restart
